apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  volumes:
    - name: hostpath
      hostPath:
        path: /demo
        type: Directory
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "12000"]
      volumeMounts:
        - mountPath: /data
          name: hostpath
