kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-disk
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
kind: Pod
apiVersion: v1
metadata:
  name: ebs-demo
spec:
  volumes:
    - name: ebs-disk
      persistentVolumeClaim:
        claimName: ebs-disk

  containers:
    - name: centos
      image: centos:7
      command:
        - "sleep"
        - "10000"
      volumeMounts:
        - mountPath: /data
          name: ebs-disk